app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/',        'homeController@index');
Route::get('test',     'homeController@test');
Route::get('login',    'homeController@login');
Route::get('registro', 'homeController@registro');

Route::resource('user', 'userController');
Route::resource('log',  'logController');
Route::get('logout',  'logController@logout');

Route::resource('vehiculo', 'carController');
Route::get('vehiculo/{id}/historial/', [
  'as'   => 'vehiculo.historial',
  'uses' => 'carController@historial'
]);
Route::get('ubicacion/',  ['as' => 'car.ubicacion', 'uses' => 'carController@ubicacion']);
Route::get('vehiculo/{imei}/ubicacion', ['as' => 'vehiculo.map', 'uses' => 'carController@map']);

Route::resource('loc', 'locController');
Route::get('script', ['as' => 'script', 'uses' => 'locController@script']);

Route::get('estadisticas/{fecha?}', ['as' => 'estadisticas', 'uses' => 'carController@estadisticas']);

app/Car.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model {
  
  protected $table = 'cars';
  protected $fillable = [
    'imei',
    'telefono',
    'marca',
    'modelo',
    'placa',
    'color',
    'estado',
    'lim_velocidad',
    'lim_local',
    'user_id'
  ];

}

app/Http/Controllers/carController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Car;
use App\User;
use App\Location;

use Illuminate\Http\Request;
use Session;
use Redirect;
use Auth;
use DB;
use Carbon\Carbon;


class carController extends Controller {
	public $title = "Trackr";
	public $descr = "Sistema de trackeo";

	public function __construct(){
		$this->middleware('auth');    
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$user 	   = Auth::user()->id;
		$vehiculos = DB::table('cars')->where('user_id', $user)->get();
		return view('car.index', [
	    'title' => $this->title." | Vehiculos",
	    'desc'  => $this->descr,
	    'slug'  => "car.index",
	  ], compact('vehiculos'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('car.create', [
			'title' => $this->title." | Agregar Vehiculo",
			'desc'  => $this->descr,
			'slug'  => "car.create"
			]);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		$this->validate($request, [
			'imei' => 'required|unique:cars',
			'telefono' => 'required',
			'marca'    => 'required',
			'modelo'   => 'required',
			'placa'    => 'required',
			'color'    => 'required'
			]);

		$r = $request->all();
		if ( $request->ajax()){
			Car::create([
				'imei'          => $r['imei'], 
				'telefono'      => $r['telefono'],
				'marca'         => $r['marca'],
				'modelo'        => $r['modelo'],
				'placa'         => $r['placa'],
				'color'         => $r['color'],
				'estado'        => 'Encendido',
				'lim_velocidad' => $r['lim_velocidad'],
				'lim_local'     => json_encode($r['lim_local']),
				'user_id'       => Auth::user()->id
			]);
			Session::flash('message-success', 'Vehiculo agregado correctamente');
			return response()->json([
				"mensaje-success" => "Vehiculo agregado con exito"]);
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$vehiculo = Car::find($id);
		return view('car.edit', [
			'title' => $this->title." | Editar vehiculo",
			'desc'  => $this->descr,
			'slug'  => "car.edit",
			'car'   => $vehiculo
			]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, Request $request)
	{
		$vehiculo = Car::find($id);
		$r = $request->all();
		$vehiculo->fill([
			'imei'          => $r['imei'], 
			'telefono'      => $r['telefono'],
			'marca'         => $r['marca'],
			'modelo'        => $r['modelo'],
			'placa'         => $r['placa'],
			'color'         => $r['color'],
			'estado'        => 'Encendido',
			'lim_velocidad' => $r['lim_velocidad'],
			'lim_local'     => json_encode($r['lim_local']),
		]);
		$vehiculo->save();

		Session::flash('message-success', 'Vehiculo actualizado correctamente');
		return response()->json([
			"mensaje-success" => "Vehiculo actualizado con exito"]);

		Session::flash('message-success', 'Vehiculo actualizado con exito');
		return Redirect::to('/vehiculo');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Car::destroy($id);
		Session::flash('message-success', 'Vehiculo eliminado con exito');
		return Redirect::to('/vehiculo');
	}


	// HISTORIAL
	public function historial($id)
	{	
		$vehiculo = Car::find($id);
		$locs = DB::table('locs')->where('car_imei', $vehiculo['imei'])->get();
		return view('car.historial', [
			'title' => $this->title." | Historial de ubicaciones de vehiculo",
			'desc'  => $this->descr,
			'slug'  => "car.historial",
			'car'   => $vehiculo
			], compact('locs'));
	}
	// HISTORIAL

	public function ubicacion(Request $request){
		return view('car.ubicacion', [
			'title' => $this->title." | Ubicacion de vehiculo",
			'desc'  => $this->descr,
			'slug'  => "car.ubicacion",
			'lat'   => $request['lat'],
			'lng'   => $request['lng']
			]);
	}

	public function map($imei){
		return view('car.map', [
			'title' => $this->title." | Ubicacion de vehiculo",
			'desc'  => $this->descr,
			'slug'  => "car.map",
			"imei"  => $imei
			]);
	}

	public function estadisticas($fecha = 0)
	{	
		$rawCars    = $rawLoc = $jsonCars = $jsonLoc =  array();
		$distanciaP = $velocidadP = 0;
		$user       = Auth::user()->id;
		$cars       = DB::table('cars')->where('user_id',$user)->get();

		foreach ($cars as $carros) {
			$rawCars['imei']   = $carros->imei;
			$rawCars['marca']  = $carros->marca;
			$rawCars['modelo'] = $carros->modelo;
			$rawCars['placa']  = $carros->placa;

			$loc = DB::table('locs')->where('car_imei',$carros->imei)->get();
			$jsonLoc = array();
			$distanciaP = $velocidadP = $tam = 0;
			$tam = count($loc);
			foreach ($loc as $locat) {
				$distanciaP = $distanciaP + $locat->distancia;
				$velocidadP = $velocidadP + $locat->velocidad/$tam;
			}
			$rawCars['distancia'] = number_format($distanciaP, 1);
			$rawCars['velocidad'] = number_format($velocidadP, 1);
			$rawCars['tamano'] = $tam;
			array_push($jsonCars,$rawCars);
		}
		// return $jsonCars;
		return view('car.estadisticas', [
		'title'    => $this->title." | Estadisticas de vehiculos",
		'desc'     => $this->descr,
		'slug'     => "estadisticas",
		"fecha"    => $fecha,
		"jsonCars" => $jsonCars
		]);
	}
}

resources/views/car/create.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)

@section('content')
<div class="page-wrap has-header">

  <div class="container form-registro">
    <h1>Agregar vehiculo</h1>
    <hr class="full left">

    {!!Form::open([
      'route'  => 'vehiculo.store',
      'method' => 'POST',
      'class'  => 'form-horizontal'
    ])!!}

    <input type="hidden" name="_token" value="{{csrf_token()}}" id="token">

    @include('car.form')
    <div class="form-group text-center">
      <div class="col-sm-offset-2 col-sm-10">
        {!! link_to('#', 'Aceptar', ['id' => 'carStore', 'class' => 'btn btn-primary']) !!}
        {!! link_to('/vehiculo', 'Cancelar', ['class' => 'btn btn-warning']) !!}

      </div>
    </div>
    
    {!!Form::close()!!}
  </div>

</div>
@stop
   

resources/views/car/edit.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)

@section('content')
<div class="page-wrap has-header">
    
  <div class="container form-registro">
    <h1>Editar vehiculo</h1>
    <hr class="fullw left">

    {!!Form::model($car, [
      'route'  => ['vehiculo.update', $car->id],
      'method' => 'PUT',
      'class'  => 'form-horizontal'
    ])!!}

      @include('car.form')

      <input type="hidden" name="_token" value="{{csrf_token()}}" id="token">
      <input type="hidden" name="id" value="{{$car->id}}" id="id">
      <input type="hidden" name="lim_local" value="{{$car->lim_local}}" id="lim_local">

      <div class="form-group text-center">
        <div class="col-sm-offset-2 col-sm-10">
          {!! link_to('#', 'Aceptar', ['id' => 'carUpdate', 'class' => 'btn btn-primary']) !!}
          {!! link_to('/vehiculo', 'Cancelar', ['class' => 'btn btn-warning']) !!}
        </div>
      </div>
    {!!Form::close()!!}


    {!!Form::open([
      'route'  => ['vehiculo.destroy', $car->id],
      'method' => 'DELETE',
      'class'  => 'form-horizontal'
    ])!!}
      <div class="form-group text-center">
        <div class="col-sm-offset-2 col-sm-10">
          {!!Form::submit('Eliminar',['class' => 'btn btn-danger'])!!}
        </div>
      </div>
    {!!Form::close()!!}
  </div>

</div>
@stop

resources/views/car/estadisticas.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)

@section('content')
  <div class="page-wrap has-header">
    
    <div class="container">
      <h1 class="text-center">Estadisticas</h1>
      <hr>

      <p>
        <form action="" class="form-inline">
          
        </form>
      </p>
      @foreach( $jsonCars as $car)
      <div class="panel panel-default">
        <div class="panel-heading">{{$car['marca']}} // {{$car['modelo']}} // {{$car['placa']}}</div>
        <div class="panel-body">

          <table class="table table-striped table-hover">
            <tr>
              <th>Velocidad promedio:</th>
              <td>{{$car['velocidad']}} km/h</td>
            </tr>
            <tr>
              <th>Distancia recorrida:</th>
              <td>{{$car['distancia']}} mts</td>
            </tr>
          </table>
        </div>
      </div>
      @endforeach

    </div>
  </div>
@stop
    

resources/views/car/form.blade.php
<div class="form-group">
  {!!Form::label('imei', 'IMEI', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('imei',null ,['id' => 'imei', 'class' => 'form-control', 'placeholder' => "Introduzca IMEI del dispositivo", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  {!!Form::label('telefono', 'Telefono', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('telefono',null ,['id' => 'telefono','class' => 'form-control', 'placeholder' => "Introduzca linea telefonica del dispositivo", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  {!!Form::label('marca', 'Marca', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('marca',null ,['id' => 'marca','class' => 'form-control', 'placeholder' => "Introduzca la marca del vehiculo", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  {!!Form::label('modelo', 'Modelo', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('modelo',null ,['id' => 'modelo','class' => 'form-control', 'placeholder' => "Introduzca el modelo del vehiculo", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  {!!Form::label('placa', 'Placa', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('placa',null ,['id' => 'placa','class' => 'form-control', 'placeholder' => "Introduzca la placa del vehiculo", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  {!!Form::label('color', 'Color', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('color',null ,['id' => 'color','class' => 'form-control', 'placeholder' => "Introduzca el color del vehiculo", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  {!!Form::label('lim_velocidad', 'Limite de velocidad', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::number('lim_velocidad',null ,['id' => 'lim_velocidad','class' => 'form-control', 'placeholder' => "Introduzca el limite de velocidad", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  <label for="input_map" class="control-label col-sm-2">Restriccion de localidad</label>
  <div class="col-sm-10">
    <div id="input_map" name="input_map" class="form-control form-map"></div>
  </div>
</div>

resources/views/car/historial.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)

@section('content')
<div class="page-wrap has-header">

  <div class="container">
    <h1 class="text-center">Historial de ubicaciones</h1>
    <p class="text-center"> <b>{{$car->marca}}</b> // <b>{{$car->modelo}}</b> // <b>{{$car->placa}}</b> </p>
    <hr>

    <p>
      <form action="" class="form-inline text-center">
        <div class="input-group">
          <input type="text" class="form-control" id="filter" name="filter" placeholder="filtrar">
          <div class="input-group-addon"> <span class="glyphicon glyphicon-search"></span></div>
        </div>
     </form>
   </p>

   <div class="panel panel-default">
    <div class="panel-heading"></div>
    <div class="panel-body">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Direccion</th>
            <th>Fecha</th>
            <th>Hora</th>
            <th>Velocidad</th>
            <th>Distancia</th>
          </tr>
        </thead>
        <tbody class="searchable">
          @foreach($locs as $loc)
            <tr>
              <td>{{$loc->dir}}</td>
              <td><?php echo date ('d/m/Y', strtotime($loc->fecha_hora)); ?></td>
              <td><?php echo date ('h:m:s a', strtotime($loc->fecha_hora)); ?></td>
              <td>{{$loc->velocidad}} km/h</td>
              <td>{{$loc->distancia}} mts</td>
              <td class="shrink">
                {!!Form::open([
                  'route'  => 'car.ubicacion',
                  'method' => 'GET',
                  ])!!}
                  <input type="hidden" name="lat" value="{{$loc->lat}}" id="lat">
                  <input type="hidden" name="lng" value="{{$loc->lng}}" id="lng">
                  <button type="submit" class="btn btn-sm btn-success">Ver en mapa  <span class="glyphicon glyphicon-map-marker"></span></button>
                {!!Form::close()!!}
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>

</div>
</div>
@stop

resources/views/car/index.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)


@section('content')
<div class="page-wrap has-header">
  <div class="container">
    <h1 class="text-center">Vehiculos</h1>
    <hr>  

    @include('alerts.success')
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>IMEI</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Placa</th>
            <th><i class="glyphicon glyphicon-option-horizontal"></i></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
              {!! link_to_route('vehiculo.create', 'Agregar nuevo vehiculo', null, ['class' => 'btn btn-default btn-sm btn-primary'])!!}
            </td>
          </tr>
          @foreach($vehiculos as $car)
          <tr>
            <td> {{ $car->imei }} </td>
            <td> {{ $car->marca }} </td>
            <td> {{ $car->modelo }} </td>
            <td> {{ $car->placa }} </td>
            <td class="shrink">
              {!! link_to_route('vehiculo.map',     'Ver Ubicacion',   $car->imei, ['class' => 'btn btn-default btn-sm btn-primary'])!!}
              {!! link_to_route('vehiculo.historial', 'Ver Historial',   $car->id, ['class' => 'btn btn-default btn-sm btn-success'])!!}
              {!! link_to_route('vehiculo.edit',      'Editar Vehiculo', $car->id, ['class' => 'btn btn-default btn-sm btn-warning'])!!}
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>    

</div>
@stop

resources/views/car/map.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)

@section('content')
	<div class="has-header"></div>
  <input type="hidden" id="imei" name="imei" value="{{$imei}}">
	<div class="map-container">
    <div id="carMap" class="map"></div>
  </div>
@stop
    

resources/views/car/ubicacion.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)

@section('content')
	<div class="has-header"></div>
	<div class="map-container">
    <div id="ubicacionMap" class="map"></div>
  </div>
@stop
    

resources/views/car/ubicaciones.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)


@section('content')
<div class="page-wrap has-header">
  <div class="container">
    <h1 class="text-center">Ubicaciones "{{$imei}}"</h1>
    <hr>  

    <!-- MENSAJE -->
    @if( Session::has('message'))
      <div class="alert alert-success alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ Session::get('message')}}
      </div>
    @endif
    <!-- MENSAJE -->

    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>IMEI</th>
          <th>Longitud</th>
          <th>Latitud</th>
          <th>Direccion</th>
          <th>Fecha y Hora</th>
          <th>velocidad</th>
          <th>distancia</th>
          <th><i class="glyphicon glyphicon-option-horizontal"></i></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      @foreach($vehiculo as $car)
        <tr>
          <td>{{$car->imei_car}}</td>
          <td>{{$car->longitud}}</td>
          <td>{{$car->latitud}}</td>
          <td>{{$car->direccion}}</td>
          <td>{{$car->fecha_hora}}</td>
          <td>{{$car->velocidad}}</td>
          <td>{{$car->distancia}}</td>
        </tr>
      @endforeach
      </tbody>
    </table>
  </div>    

</div>
@stop
   